### Sign up
POST http://localhost:8080/v1/auth/signup
Content-Type: application/json

{
  "email": "marckraw@icloud.com",
  "password": "123456789"
}

### Sign In
POST http://localhost:8080/v1/auth/signin
Content-Type: application/json

{
  "email": "marckraw@icloud.com",
  "password": "123456789"
}

### Sign Out
GET http://localhost:8080/v1/auth/signout

### Get logged in user
GET http://localhost:8080/v1/auth/me

### DELETE user by id
DELETE http://localhost:8080/v1/auth/fe7f0896-cf5e-489c-99e7-09dcc3bd07b4

### PATCH user by id
PATCH http://localhost:8080/v1/auth/22a5471c-b870-4d29-bc16-cdfc2eab1a1c
Content-Type: application/json

{
  "email": "marckraw@icloud.com"
}

### GET user by id
GET http://localhost:8080/v1/auth/22a5471c-b870-4d29-bc16-cdfc2eab1a1c

### GET find all users with email
GET http://localhost:8080/v1/auth?email=marckraw@icloud.com